import type { VisionEdgeSpec, VisionNodeSpec } from '@/lib/admin/workflow-canvas/types'

const COL = {
  ingest: 0,
  scrape: 1,
  gate: 2,
  graph: 3,
  proposition: 4,
  debate: 5,
  complete: 6,
} as const

export const VISION_FLOW_NODES: VisionNodeSpec[] = [
  {
    id: 'relevance-gate',
    visionLabel: 'Qualify story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'relevance-gate',
    decisionMode: 'qualify',
    lane: 'main',
    column: COL.ingest,
    row: 0,
  },
  {
    id: 'review-pending-stories',
    visionLabel: 'Pending approval',
    nodeType: 'decision',
    maturity: 'live',
    catalogStepId: 'review-pending-stories',
    decisionMode: 'approval',
    lane: 'main',
    column: COL.ingest,
    row: 1,
  },
  {
    id: 'vision:stop',
    visionLabel: 'Stop',
    nodeType: 'terminal',
    maturity: 'placeholder',
    roadmapNote: 'Story dropped — no further pipeline steps.',
    lane: 'main',
    column: COL.ingest,
    row: 2,
  },
  {
    id: 'scrape-story-content',
    visionLabel: 'Scrape story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'scrape-story-content',
    iconVariant: 'cloud',
    lane: 'main',
    column: COL.scrape,
    row: 0,
  },
  {
    id: 'clean-scraped-content',
    visionLabel: 'Clean scraped content',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'clean-scraped-content',
    lane: 'main',
    column: COL.gate,
    row: 0,
  },
  {
    id: 'enqueue-graph-job',
    visionLabel: 'Enqueue graph job',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'enqueue-graph-job',
    lane: 'main',
    column: COL.graph,
    row: 0,
  },
  {
    id: 'trigger-graph-worker',
    visionLabel: 'Build knowledge graph',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'trigger-graph-worker',
    roadmapNote:
      'Wakes Python neo4j-graphrag worker; Phase 0–2a (utterances, propositions, arguments) via graph_processing_jobs.',
    lane: 'main',
    column: COL.graph,
    row: 1,
  },
  {
    id: 'vision:proposition-layer',
    visionLabel: 'Proposition layer',
    nodeType: 'agent',
    maturity: 'live',
    roadmapNote:
      'In-worker Phase 1: Proposition EXPRESSES + Entity ER (same graph job as utterances).',
    lane: 'main',
    column: COL.proposition,
    row: 0,
  },
  {
    id: 'debate-pipeline',
    visionLabel: 'Debate assembly',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'debate-pipeline',
    roadmapNote:
      'Cross-document Viewpoint / Controversy / Dispute + Supabase projections (Neo SoT).',
    lane: 'main',
    column: COL.debate,
    row: 0,
  },
  {
    id: 'vision:complete',
    visionLabel: 'Complete',
    nodeType: 'terminal',
    maturity: 'live',
    roadmapNote: 'Primary Neo debate path finished for this cycle.',
    lane: 'main',
    column: COL.complete,
    row: 0,
  },
]

export const VISION_FLOW_EDGES: VisionEdgeSpec[] = [
  { id: 'e-gate-keep', source: 'relevance-gate', target: 'scrape-story-content', sourceHandle: 'pass', kind: 'pass' },
  { id: 'e-gate-drop', source: 'relevance-gate', target: 'vision:stop', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-gate-pending', source: 'relevance-gate', target: 'review-pending-stories', sourceHandle: 'pending', kind: 'neutral' },
  { id: 'e-pending-keep', source: 'review-pending-stories', target: 'scrape-story-content', sourceHandle: 'pass', kind: 'pass' },
  { id: 'e-pending-drop', source: 'review-pending-stories', target: 'vision:stop', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-scrape-clean', source: 'scrape-story-content', target: 'clean-scraped-content', kind: 'pass' },
  { id: 'e-clean-enqueue', source: 'clean-scraped-content', target: 'enqueue-graph-job', kind: 'pass' },
  { id: 'e-enqueue-trigger', source: 'enqueue-graph-job', target: 'trigger-graph-worker', kind: 'pass' },
  { id: 'e-trigger-prop', source: 'trigger-graph-worker', target: 'vision:proposition-layer', kind: 'pass' },
  { id: 'e-prop-debate', source: 'vision:proposition-layer', target: 'debate-pipeline', kind: 'pass' },
  { id: 'e-debate-complete', source: 'debate-pipeline', target: 'vision:complete', kind: 'pass' },
]

export function getVisionNodeById(id: string): VisionNodeSpec | undefined {
  return VISION_FLOW_NODES.find((n) => n.id === id)
}
