import type { VisionEdgeSpec, VisionNodeSpec } from '@/lib/admin/workflow-canvas/types'

const ARCHIVED_ROADMAP_NOTE =
  'Archived — handler moved to legacy/. Re-enable in catalog when rebuilt iteratively.'

const DEPRECATED_CLAIMS_NOTE =
  'Deprecated — replaced by Neo4j utterance graph-worker (Phase 0). Pending cleanup after Phase 2.'

const COL = {
  ingest: 0,
  scrape: 1,
  gate: 2,
  graph: 3,
  chunk: 4,
  extract: 5,
  review: 6,
  mergeLane: 7,
  mergeHub: 8,
  mergeQa: 9,
  canonical: 10,
  downstream: 11,
} as const

export const VISION_FLOW_NODES: VisionNodeSpec[] = [
  {
    id: 'relevance-gate',
    visionLabel: 'Qualify story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'relevance-gate',
    decisionMode: 'qualify',
    lane: 'main',
    column: COL.ingest,
    row: 0,
  },
  {
    id: 'review-pending-stories',
    visionLabel: 'Pending approval',
    nodeType: 'decision',
    maturity: 'live',
    catalogStepId: 'review-pending-stories',
    decisionMode: 'approval',
    lane: 'main',
    column: COL.ingest,
    row: 1,
  },
  {
    id: 'vision:stop',
    visionLabel: 'Stop',
    nodeType: 'terminal',
    maturity: 'placeholder',
    roadmapNote: 'Story dropped — no further pipeline steps.',
    lane: 'main',
    column: COL.ingest,
    row: 2,
  },
  {
    id: 'scrape-story-content',
    visionLabel: 'Scrape story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'scrape-story-content',
    iconVariant: 'cloud',
    lane: 'main',
    column: COL.scrape,
    row: 0,
  },
  {
    id: 'clean-scraped-content',
    visionLabel: 'Clean scraped content',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'clean-scraped-content',
    lane: 'main',
    column: COL.gate,
    row: 0,
  },
  {
    id: 'enqueue-graph-job',
    visionLabel: 'Enqueue graph job',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'enqueue-graph-job',
    lane: 'main',
    column: COL.graph,
    row: 0,
  },
  {
    id: 'trigger-graph-worker',
    visionLabel: 'Build knowledge graph',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'trigger-graph-worker',
    roadmapNote:
      'Wakes Python neo4j-graphrag worker; processing is async via graph_processing_jobs.',
    lane: 'main',
    column: COL.graph,
    row: 1,
  },
  {
    id: 'chunk-story-bodies',
    visionLabel: 'Chunk story',
    nodeType: 'agent',
    maturity: 'partial',
    catalogStepId: 'chunk-story-bodies',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'main',
    column: COL.chunk,
    row: 1,
  },
  // Claims lane — deprecated (Neo4j hybrid).
  {
    id: 'vision:process-k-claims',
    visionLabel: 'Process K-Claims',
    nodeType: 'agent',
    maturity: 'partial',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'claims',
    column: COL.extract,
    row: 0,
    opensChunkWorkflows: true,
    chunkProgressLane: 'claims',
  },
  {
    id: 'merge-story-claims',
    visionLabel: 'Merge claims',
    nodeType: 'merge',
    maturity: 'partial',
    catalogStepId: 'merge-story-claims',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'claims',
    column: COL.mergeLane,
    row: 0,
  },

  // Positions lane
  {
    id: 'extract-story-positions',
    visionLabel: 'Position Extractor',
    nodeType: 'agent',
    maturity: 'partial',
    catalogStepId: 'extract-story-positions',
    roadmapNote: ARCHIVED_ROADMAP_NOTE,
    lane: 'positions',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'validate-chunk-positions',
    visionLabel: 'Position Reviewer',
    nodeType: 'decision',
    maturity: 'partial',
    catalogStepId: 'validate-chunk-positions',
    roadmapNote: ARCHIVED_ROADMAP_NOTE,
    lane: 'positions',
    column: COL.review,
    row: 0,
  },
  {
    id: 'refine-chunk-positions',
    visionLabel: 'Position Refiner',
    nodeType: 'agent',
    maturity: 'partial',
    catalogStepId: 'refine-chunk-positions',
    roadmapNote: ARCHIVED_ROADMAP_NOTE,
    lane: 'positions',
    column: COL.review,
    row: 1,
  },
  {
    id: 'merge-story-positions',
    visionLabel: 'Merge positions',
    nodeType: 'merge',
    maturity: 'partial',
    catalogStepId: 'merge-story-positions',
    roadmapNote: ARCHIVED_ROADMAP_NOTE,
    lane: 'positions',
    column: COL.mergeLane,
    row: 0,
  },

  // Events lane (partial)
  {
    id: 'vision:extract-story-events',
    visionLabel: 'Event Extractor',
    nodeType: 'agent',
    maturity: 'partial',
    handlerPath: 'doxa-agents/departments/legacy/02-chunking-engine/11-extract-story-events',
    roadmapNote: 'Per-chunk event extraction — stub README only; handler not implemented.',
    lane: 'events',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'vision:validate-chunk-events',
    visionLabel: 'Event Reviewer',
    nodeType: 'decision',
    maturity: 'placeholder',
    lane: 'events',
    column: COL.review,
    row: 0,
  },
  {
    id: 'vision:refine-chunk-events',
    visionLabel: 'Event Refiner',
    nodeType: 'agent',
    maturity: 'placeholder',
    lane: 'events',
    column: COL.review,
    row: 1,
  },
  {
    id: 'vision:merge-story-events',
    visionLabel: 'Merge events',
    nodeType: 'merge',
    maturity: 'placeholder',
    lane: 'events',
    column: COL.mergeLane,
    row: 0,
  },

  // Evidence lane (partial)
  {
    id: 'vision:extract-story-evidence',
    visionLabel: 'Evidence Extractor',
    nodeType: 'agent',
    maturity: 'partial',
    handlerPath: 'doxa-agents/departments/legacy/02-chunking-engine/07-extract-story-evidence',
    roadmapNote: 'Per-chunk evidence extraction — stub README only; handler not implemented.',
    lane: 'evidence',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'vision:validate-chunk-evidence',
    visionLabel: 'Evidence Reviewer',
    nodeType: 'decision',
    maturity: 'placeholder',
    lane: 'evidence',
    column: COL.review,
    row: 0,
  },
  {
    id: 'vision:refine-chunk-evidence',
    visionLabel: 'Evidence Refiner',
    nodeType: 'agent',
    maturity: 'placeholder',
    lane: 'evidence',
    column: COL.review,
    row: 1,
  },
  {
    id: 'vision:merge-story-evidence',
    visionLabel: 'Merge evidence',
    nodeType: 'merge',
    maturity: 'placeholder',
    lane: 'evidence',
    column: COL.mergeLane,
    row: 0,
  },

  {
    id: 'vision:story-relationship-mapping',
    visionLabel: 'Story Graphing',
    nodeType: 'agent',
    maturity: 'partial',
    roadmapNote:
      'Superseded by Neo4j Phase 0 utterance graph-worker (Document/Segment/Utterance). Proposition + debate topology are later phases.',
    lane: 'main',
    column: COL.mergeHub,
    row: 0,
  },
]

/** Per-chunk claims QA steps — used by the chunk workflow canvas only. */
export const CHUNK_CLAIMS_VISION_NODES: VisionNodeSpec[] = [
  {
    id: 'extract-story-claims',
    visionLabel: 'Claim Extractor',
    nodeType: 'agent',
    maturity: 'partial',
    catalogStepId: 'extract-story-claims',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'claims',
    column: 0,
    row: 0,
  },
  {
    id: 'validate-chunk-claims',
    visionLabel: 'Claim Reviewer',
    nodeType: 'decision',
    maturity: 'partial',
    catalogStepId: 'validate-chunk-claims',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'claims',
    column: 1,
    row: 0,
  },
  {
    id: 'refine-chunk-claims',
    visionLabel: 'Claim Refiner',
    nodeType: 'agent',
    maturity: 'partial',
    catalogStepId: 'refine-chunk-claims',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'claims',
    column: 2,
    row: 0,
  },
  {
    id: 'approve-chunk-claims',
    visionLabel: 'Claim Approver',
    nodeType: 'decision',
    maturity: 'partial',
    catalogStepId: 'approve-chunk-claims',
    roadmapNote: DEPRECATED_CLAIMS_NOTE,
    lane: 'claims',
    column: 3,
    row: 0,
  },
]

export const VISION_FLOW_EDGES: VisionEdgeSpec[] = [
  { id: 'e-gate-keep', source: 'relevance-gate', target: 'scrape-story-content', sourceHandle: 'pass', kind: 'pass' },
  { id: 'e-gate-drop', source: 'relevance-gate', target: 'vision:stop', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-gate-pending', source: 'relevance-gate', target: 'review-pending-stories', sourceHandle: 'pending', kind: 'neutral' },
  { id: 'e-pending-keep', source: 'review-pending-stories', target: 'scrape-story-content', sourceHandle: 'pass', kind: 'pass' },
  { id: 'e-pending-drop', source: 'review-pending-stories', target: 'vision:stop', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-scrape-clean', source: 'scrape-story-content', target: 'clean-scraped-content', kind: 'pass' },
  { id: 'e-clean-enqueue', source: 'clean-scraped-content', target: 'enqueue-graph-job', kind: 'pass' },
  { id: 'e-enqueue-trigger', source: 'enqueue-graph-job', target: 'trigger-graph-worker', kind: 'pass' },
  { id: 'e-clean-chunk', source: 'clean-scraped-content', target: 'chunk-story-bodies', kind: 'neutral' },
  { id: 'e-chunk-c', source: 'chunk-story-bodies', target: 'vision:process-k-claims', kind: 'neutral' },
  { id: 'e-chunk-p', source: 'chunk-story-bodies', target: 'extract-story-positions', kind: 'neutral' },
  { id: 'e-chunk-e', source: 'chunk-story-bodies', target: 'vision:extract-story-events', kind: 'neutral' },
  { id: 'e-chunk-v', source: 'chunk-story-bodies', target: 'vision:extract-story-evidence', kind: 'neutral' },

  { id: 'e-c-process-merge', source: 'vision:process-k-claims', target: 'merge-story-claims', kind: 'neutral' },

  { id: 'e-p-ext-rev', source: 'extract-story-positions', target: 'validate-chunk-positions', kind: 'pass' },
  { id: 'e-p-rev-ref', source: 'validate-chunk-positions', target: 'refine-chunk-positions', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-p-ref-rev', source: 'refine-chunk-positions', target: 'validate-chunk-positions', targetHandle: 'top', kind: 'return' },
  { id: 'e-p-rev-merge', source: 'validate-chunk-positions', target: 'merge-story-positions', sourceHandle: 'pass', kind: 'pass' },

  { id: 'e-e-ext-rev', source: 'vision:extract-story-events', target: 'vision:validate-chunk-events', kind: 'neutral' },
  { id: 'e-e-rev-ref', source: 'vision:validate-chunk-events', target: 'vision:refine-chunk-events', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-e-ref-rev', source: 'vision:refine-chunk-events', target: 'vision:validate-chunk-events', targetHandle: 'top', kind: 'return' },
  { id: 'e-e-rev-merge', source: 'vision:validate-chunk-events', target: 'vision:merge-story-events', sourceHandle: 'pass', kind: 'neutral' },

  { id: 'e-v-ext-rev', source: 'vision:extract-story-evidence', target: 'vision:validate-chunk-evidence', kind: 'neutral' },
  { id: 'e-v-rev-ref', source: 'vision:validate-chunk-evidence', target: 'vision:refine-chunk-evidence', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-v-ref-rev', source: 'vision:refine-chunk-evidence', target: 'vision:validate-chunk-evidence', targetHandle: 'top', kind: 'return' },
  { id: 'e-v-rev-merge', source: 'vision:validate-chunk-evidence', target: 'vision:merge-story-evidence', sourceHandle: 'pass', kind: 'neutral' },

  {
    id: 'e-mc-sg',
    source: 'merge-story-claims',
    target: 'vision:story-relationship-mapping',
    kind: 'pass',
  },
  {
    id: 'e-mp-sg',
    source: 'merge-story-positions',
    target: 'vision:story-relationship-mapping',
    kind: 'pass',
  },
  {
    id: 'e-me-sg',
    source: 'vision:merge-story-events',
    target: 'vision:story-relationship-mapping',
    kind: 'neutral',
  },
  {
    id: 'e-mv-sg',
    source: 'vision:merge-story-evidence',
    target: 'vision:story-relationship-mapping',
    kind: 'neutral',
  },
]

/** Linear claims QA on the chunk canvas (no approve→refine loop or merge edges). */
export const CHUNK_CLAIMS_VISION_EDGES: VisionEdgeSpec[] = [
  { id: 'e-c-ext-rev', source: 'extract-story-claims', target: 'validate-chunk-claims', kind: 'pass' },
  { id: 'e-c-rev-ref', source: 'validate-chunk-claims', target: 'refine-chunk-claims', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-c-ref-apr', source: 'refine-chunk-claims', target: 'approve-chunk-claims', kind: 'pass' },
]

export function getVisionNodeById(id: string): VisionNodeSpec | undefined {
  return (
    VISION_FLOW_NODES.find((n) => n.id === id) ??
    CHUNK_CLAIMS_VISION_NODES.find((n) => n.id === id)
  )
}
