import type { VisionEdgeSpec, VisionNodeSpec } from '@/lib/admin/workflow-canvas/types'

const COL = {
  ingest: 0,
  scrape: 1,
  gate: 2,
  chunk: 3,
  extract: 4,
  review: 5,
  mergeLane: 6,
  mergeHub: 7,
  mergeQa: 8,
  canonical: 9,
  downstream: 10,
} as const

export const VISION_FLOW_NODES: VisionNodeSpec[] = [
  {
    id: 'relevance-gate',
    visionLabel: 'Qualify story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'relevance-gate',
    decisionMode: 'qualify',
    lane: 'main',
    column: COL.ingest,
    row: 0,
  },
  {
    id: 'review-pending-stories',
    visionLabel: 'Pending approval',
    nodeType: 'decision',
    maturity: 'live',
    catalogStepId: 'review-pending-stories',
    decisionMode: 'approval',
    lane: 'main',
    column: COL.ingest,
    row: 1,
  },
  {
    id: 'vision:stop',
    visionLabel: 'Stop',
    nodeType: 'terminal',
    maturity: 'placeholder',
    roadmapNote: 'Story dropped — no further pipeline steps.',
    lane: 'main',
    column: COL.ingest,
    row: 2,
  },
  {
    id: 'scrape-story-content',
    visionLabel: 'Scrape story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'scrape-story-content',
    iconVariant: 'cloud',
    lane: 'main',
    column: COL.scrape,
    row: 0,
  },
  {
    id: 'clean-scraped-content',
    visionLabel: 'Clean scraped content',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'clean-scraped-content',
    lane: 'main',
    column: COL.gate,
    row: 0,
  },
  {
    id: 'chunk-story-bodies',
    visionLabel: 'Chunk story',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'chunk-story-bodies',
    lane: 'main',
    column: COL.chunk,
    row: 1,
  },
  // Claims lane
  {
    id: 'extract-story-claims',
    visionLabel: 'Claim Extractor',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'extract-story-claims',
    lane: 'claims',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'validate-chunk-claims',
    visionLabel: 'Claim Reviewer',
    nodeType: 'decision',
    maturity: 'live',
    catalogStepId: 'validate-chunk-claims',
    lane: 'claims',
    column: COL.review,
    row: 0,
  },
  {
    id: 'refine-chunk-claims',
    visionLabel: 'Claim Refiner',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'refine-chunk-claims',
    lane: 'claims',
    column: COL.review,
    row: 1,
  },
  {
    id: 'merge-story-claims',
    visionLabel: 'Merge claims',
    nodeType: 'merge',
    maturity: 'live',
    catalogStepId: 'merge-story-claims',
    lane: 'claims',
    column: COL.mergeLane,
    row: 0,
  },

  // Positions lane
  {
    id: 'extract-story-positions',
    visionLabel: 'Position Extractor',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'extract-story-positions',
    lane: 'positions',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'validate-chunk-positions',
    visionLabel: 'Position Reviewer',
    nodeType: 'decision',
    maturity: 'live',
    catalogStepId: 'validate-chunk-positions',
    lane: 'positions',
    column: COL.review,
    row: 0,
  },
  {
    id: 'refine-chunk-positions',
    visionLabel: 'Position Refiner',
    nodeType: 'agent',
    maturity: 'live',
    catalogStepId: 'refine-chunk-positions',
    lane: 'positions',
    column: COL.review,
    row: 1,
  },
  {
    id: 'merge-story-positions',
    visionLabel: 'Merge positions',
    nodeType: 'merge',
    maturity: 'live',
    catalogStepId: 'merge-story-positions',
    lane: 'positions',
    column: COL.mergeLane,
    row: 0,
  },

  // Events lane (partial)
  {
    id: 'vision:extract-story-events',
    visionLabel: 'Event Extractor',
    nodeType: 'agent',
    maturity: 'partial',
    handlerPath: 'doxa-agents/departments/02-chunking-engine/11-extract-story-events',
    roadmapNote: 'Per-chunk event extraction — stub README only; handler not implemented.',
    lane: 'events',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'vision:validate-chunk-events',
    visionLabel: 'Event Reviewer',
    nodeType: 'decision',
    maturity: 'placeholder',
    lane: 'events',
    column: COL.review,
    row: 0,
  },
  {
    id: 'vision:refine-chunk-events',
    visionLabel: 'Event Refiner',
    nodeType: 'agent',
    maturity: 'placeholder',
    lane: 'events',
    column: COL.review,
    row: 1,
  },
  {
    id: 'vision:merge-story-events',
    visionLabel: 'Merge events',
    nodeType: 'merge',
    maturity: 'placeholder',
    lane: 'events',
    column: COL.mergeLane,
    row: 0,
  },

  // Evidence lane (partial)
  {
    id: 'vision:extract-story-evidence',
    visionLabel: 'Evidence Extractor',
    nodeType: 'agent',
    maturity: 'partial',
    handlerPath: 'doxa-agents/departments/02-chunking-engine/07-extract-story-evidence',
    roadmapNote: 'Per-chunk evidence extraction — stub README only; handler not implemented.',
    lane: 'evidence',
    column: COL.extract,
    row: 0,
  },
  {
    id: 'vision:validate-chunk-evidence',
    visionLabel: 'Evidence Reviewer',
    nodeType: 'decision',
    maturity: 'placeholder',
    lane: 'evidence',
    column: COL.review,
    row: 0,
  },
  {
    id: 'vision:refine-chunk-evidence',
    visionLabel: 'Evidence Refiner',
    nodeType: 'agent',
    maturity: 'placeholder',
    lane: 'evidence',
    column: COL.review,
    row: 1,
  },
  {
    id: 'vision:merge-story-evidence',
    visionLabel: 'Merge evidence',
    nodeType: 'merge',
    maturity: 'placeholder',
    lane: 'evidence',
    column: COL.mergeLane,
    row: 0,
  },

  {
    id: 'vision:story-relationship-mapping',
    visionLabel: 'Story Graphing',
    nodeType: 'agent',
    maturity: 'placeholder',
    roadmapNote:
      'Future agent: build the story-level entity graph after lane merges (replaces link entities).',
    lane: 'main',
    column: COL.mergeHub,
    row: 0,
  },
]

export const VISION_FLOW_EDGES: VisionEdgeSpec[] = [
  { id: 'e-gate-keep', source: 'relevance-gate', target: 'scrape-story-content', sourceHandle: 'pass', kind: 'pass' },
  { id: 'e-gate-drop', source: 'relevance-gate', target: 'vision:stop', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-gate-pending', source: 'relevance-gate', target: 'review-pending-stories', sourceHandle: 'pending', kind: 'neutral' },
  { id: 'e-pending-keep', source: 'review-pending-stories', target: 'scrape-story-content', sourceHandle: 'pass', kind: 'pass' },
  { id: 'e-pending-drop', source: 'review-pending-stories', target: 'vision:stop', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-scrape-clean', source: 'scrape-story-content', target: 'clean-scraped-content', kind: 'pass' },
  { id: 'e-clean-chunk', source: 'clean-scraped-content', target: 'chunk-story-bodies', kind: 'pass' },
  { id: 'e-chunk-c', source: 'chunk-story-bodies', target: 'extract-story-claims', kind: 'pass' },
  { id: 'e-chunk-p', source: 'chunk-story-bodies', target: 'extract-story-positions', kind: 'pass' },
  { id: 'e-chunk-e', source: 'chunk-story-bodies', target: 'vision:extract-story-events', kind: 'neutral' },
  { id: 'e-chunk-v', source: 'chunk-story-bodies', target: 'vision:extract-story-evidence', kind: 'neutral' },

  { id: 'e-c-ext-rev', source: 'extract-story-claims', target: 'validate-chunk-claims', kind: 'pass' },
  { id: 'e-c-rev-ref', source: 'validate-chunk-claims', target: 'refine-chunk-claims', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-c-ref-rev', source: 'refine-chunk-claims', target: 'validate-chunk-claims', targetHandle: 'top', kind: 'return' },
  { id: 'e-c-rev-merge', source: 'validate-chunk-claims', target: 'merge-story-claims', sourceHandle: 'pass', kind: 'pass' },

  { id: 'e-p-ext-rev', source: 'extract-story-positions', target: 'validate-chunk-positions', kind: 'pass' },
  { id: 'e-p-rev-ref', source: 'validate-chunk-positions', target: 'refine-chunk-positions', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-p-ref-rev', source: 'refine-chunk-positions', target: 'validate-chunk-positions', targetHandle: 'top', kind: 'return' },
  { id: 'e-p-rev-merge', source: 'validate-chunk-positions', target: 'merge-story-positions', sourceHandle: 'pass', kind: 'pass' },

  { id: 'e-e-ext-rev', source: 'vision:extract-story-events', target: 'vision:validate-chunk-events', kind: 'neutral' },
  { id: 'e-e-rev-ref', source: 'vision:validate-chunk-events', target: 'vision:refine-chunk-events', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-e-ref-rev', source: 'vision:refine-chunk-events', target: 'vision:validate-chunk-events', targetHandle: 'top', kind: 'return' },
  { id: 'e-e-rev-merge', source: 'vision:validate-chunk-events', target: 'vision:merge-story-events', sourceHandle: 'pass', kind: 'neutral' },

  { id: 'e-v-ext-rev', source: 'vision:extract-story-evidence', target: 'vision:validate-chunk-evidence', kind: 'neutral' },
  { id: 'e-v-rev-ref', source: 'vision:validate-chunk-evidence', target: 'vision:refine-chunk-evidence', sourceHandle: 'fail', kind: 'fail' },
  { id: 'e-v-ref-rev', source: 'vision:refine-chunk-evidence', target: 'vision:validate-chunk-evidence', targetHandle: 'top', kind: 'return' },
  { id: 'e-v-rev-merge', source: 'vision:validate-chunk-evidence', target: 'vision:merge-story-evidence', sourceHandle: 'pass', kind: 'neutral' },

  {
    id: 'e-mc-sg',
    source: 'merge-story-claims',
    target: 'vision:story-relationship-mapping',
    kind: 'pass',
  },
  {
    id: 'e-mp-sg',
    source: 'merge-story-positions',
    target: 'vision:story-relationship-mapping',
    kind: 'pass',
  },
  {
    id: 'e-me-sg',
    source: 'vision:merge-story-events',
    target: 'vision:story-relationship-mapping',
    kind: 'neutral',
  },
  {
    id: 'e-mv-sg',
    source: 'vision:merge-story-evidence',
    target: 'vision:story-relationship-mapping',
    kind: 'neutral',
  },
]

export function getVisionNodeById(id: string): VisionNodeSpec | undefined {
  return VISION_FLOW_NODES.find((n) => n.id === id)
}
