import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(__dirname, '..');

export type StepStatus = 'active' | 'inactive' | 'deprecated';
export type StepKind = 'edge_function' | 'worker' | 'rpc' | 'manual' | 'maintenance_script';

export interface CronConfig {
  job_name: string;
  schedule: string;
  sql: string;
  body?: string;
}

export interface ManifestStep {
  id: string;
  deploy_name?: string;
  division: string;
  workflow: string;
  kind: StepKind;
  status: StepStatus;
  source?: string;
  cron?: CronConfig;
  invokes?: string[];
  invoked_by?: string[];
  secrets?: string[];
  tables?: string[];
  verify_jwt?: boolean;
  description?: string;
}

export interface Manifest {
  version: number;
  vault_secrets: string[];
  workers?: Record<string, { path: string; invokes?: string[] }>;
  steps: ManifestStep[];
}

export function loadManifest(): Manifest {
  const raw = fs.readFileSync(path.join(REPO_ROOT, 'doxa-agents', 'manifest.yaml'), 'utf8');
  return yaml.parse(raw) as Manifest;
}

export function manifestPath(...parts: string[]): string {
  return path.join(REPO_ROOT, 'doxa-agents', ...parts);
}

export function supabaseFunctionsDir(): string {
  return path.join(REPO_ROOT, 'supabase', 'functions');
}

export function handlerPath(step: ManifestStep): string | null {
  if (!step.source) return null;
  return path.join(REPO_ROOT, step.source, 'handler.ts');
}

export function stubPath(deployName: string): string {
  return path.join(supabaseFunctionsDir(), deployName, 'index.ts');
}

export function relativeStubImport(deployName: string, step: ManifestStep): string {
  const stubDir = path.join(supabaseFunctionsDir(), deployName);
  const handler = handlerPath(step)!;
  let rel = path.relative(stubDir, handler).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel;
}

export function parseCronSql(sqlContent: string): Array<{ job_name: string; schedule: string; deploy_name?: string }> {
  const jobs: Array<{ job_name: string; schedule: string; deploy_name?: string }> = [];
  const scheduleRe = /cron\.schedule\(\s*'([^']+)'\s*,\s*'([^']+)'/g;
  let m: RegExpExecArray | null;
  while ((m = scheduleRe.exec(sqlContent)) !== null) {
    const job_name = m[1];
    const schedule = m[2];
    const slice = sqlContent.slice(m.index, m.index + 800);
    const fnMatch = slice.match(/\/functions\/v1\/([a-zA-Z0-9_-]+)/);
    jobs.push({ job_name, schedule, deploy_name: fnMatch?.[1] });
  }
  return jobs;
}

export function extractInvokedDeployNames(source: string): string[] {
  const names = new Set<string>();
  const urlRe = /\/functions\/v1\/([a-zA-Z0-9_-]+)/g;
  let m: RegExpExecArray | null;
  while ((m = urlRe.exec(source)) !== null) names.add(m[1]);
  const invokeRe = /invokeFunction\([^,]+,[^,]+,\s*["']([a-zA-Z0-9_-]+)["']/g;
  while ((m = invokeRe.exec(source)) !== null) names.add(m[1]);
  return [...names];
}

export function stepById(steps: ManifestStep[], id: string): ManifestStep | undefined {
  return steps.find((s) => s.id === id);
}

export function stepByDeployName(steps: ManifestStep[], deployName: string): ManifestStep | undefined {
  return steps.find((s) => s.deploy_name === deployName);
}

export const MANIFEST_BANNER =
  '# AUTO-GENERATED by npm run agents:sync — do not edit. Edit activation.yaml, handlers, or schedule SQL.\n';

export function loadActivation(): { active: string[] } {
  const raw = fs.readFileSync(path.join(REPO_ROOT, 'doxa-agents', 'activation.yaml'), 'utf8');
  const parsed = yaml.parse(raw) as { active?: string[] };
  return { active: parsed.active ?? [] };
}

export function extractSecrets(source: string): string[] {
  const skip = new Set(['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY']);
  const secrets = new Set<string>();
  const re = /Deno\.env\.get\(\s*["']([A-Z0-9_]+)["']\s*\)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) {
    if (!skip.has(m[1])) secrets.add(m[1]);
  }
  return [...secrets].sort();
}

export function parseCronBody(sqlContent: string, jobName: string): string | undefined {
  const re = new RegExp(
    `cron\\.schedule\\(\\s*'${jobName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}'\\s*,\\s*'[^']+'\\s*,\\s*\\$\\$([\\s\\S]*?)\\$\\$`,
  );
  const m = re.exec(sqlContent);
  if (!m) return undefined;
  const block = m[1];
  const bodyMatch = block.match(/body\s*:=\s*'([^']+)'::jsonb/);
  return bodyMatch?.[1];
}

export function isMaintenanceOnlySql(sqlContent: string): boolean {
  return sqlContent.includes('cron.unschedule') && !sqlContent.includes('cron.schedule');
}

export function parseVerifyJwtDisabled(configContent: string): Set<string> {
  const disabled = new Set<string>();
  const re = /\[functions\.([^\]]+)\]\s*\nverify_jwt\s*=\s*false/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(configContent)) !== null) disabled.add(m[1]);
  return disabled;
}

export function scanAppApiInvokes(): Map<string, string[]> {
  const map = new Map<string, string[]>();
  const apiDir = path.join(REPO_ROOT, 'app', 'api');
  if (!fs.existsSync(apiDir)) return map;

  function walk(dir: string) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, ent.name);
      if (ent.isDirectory()) walk(full);
      else if (ent.name.endsWith('.ts')) {
        const content = fs.readFileSync(full, 'utf8');
        for (const deploy of extractInvokedDeployNames(content)) {
          const list = map.get(deploy) ?? [];
          if (!list.includes('app')) list.push('app');
          map.set(deploy, list);
        }
      }
    }
  }
  walk(apiDir);
  return map;
}

export function jobNameToStepId(jobName: string): string {
  return jobName;
}

export const GENERATED_BANNER =
  '<!-- AUTO-GENERATED by npm run agents:docs — do not edit manually -->\n';

export const AGENTS_BEGIN = '<!-- AGENTS:BEGIN -->';
export const AGENTS_END = '<!-- AGENTS:END -->';
