import fs from 'fs';
import path from 'path';
import yaml from 'yaml';
import { GENERATED_BANNER, REPO_ROOT, loadManifest, stepById, type ManifestStep } from './agents-lib.ts';

const checkOnly = process.argv.includes('--check');

const CONFIG_PATH = path.join(REPO_ROOT, 'doxa-agents', 'ops', 'pipeline-admin-catalog.yaml');
const TS_OUT = path.join(REPO_ROOT, 'lib', 'admin', 'generated', 'pipeline-catalog.ts');
const MD_OUT = path.join(REPO_ROOT, 'doxa-agents', 'docs', 'generated', 'pipeline-catalog.md');

const TS_BANNER = `// AUTO-GENERATED by scripts/generate-pipeline-catalog.ts
// Source: doxa-agents/ops/pipeline-admin-catalog.yaml + manifest.yaml
// Regenerate: npm run agents:pipeline-catalog
`;

interface StepOverride {
  id: string;
  label: string;
  optional?: boolean;
  isolation_params?: string[];
  invoke_options?: {
    uses_max_chunks?: boolean;
    max_chunks?: number;
    timeout_ms?: number;
  };
}

interface StageConfig {
  id: string;
  label: string;
  scope: string;
  steps: StepOverride[];
}

interface AdminCatalogConfig {
  version: number;
  stages: StageConfig[];
  inactive_note?: string;
}

interface CatalogStep {
  id: string;
  deployName: string;
  label: string;
  stageId: string;
  stageLabel: string;
  scope: string;
  optional: boolean;
  manifestStatus: string;
  isolationParams: string[];
  invokeOptions: {
    usesMaxChunks: boolean;
    maxChunks: number | null;
    timeoutMs: number;
  };
  inactiveNote: string | null;
}

interface CatalogStage {
  id: string;
  label: string;
  scope: string;
  stepIds: string[];
}

function loadConfig(): AdminCatalogConfig {
  const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
  return yaml.parse(raw) as AdminCatalogConfig;
}

function mergeStep(
  override: StepOverride,
  stage: StageConfig,
  manifestStep: ManifestStep,
  inactiveNote: string | null,
): CatalogStep {
  const invoke = override.invoke_options ?? {};
  return {
    id: override.id,
    deployName: manifestStep.deploy_name!,
    label: override.label,
    stageId: stage.id,
    stageLabel: stage.label,
    scope: stage.scope,
    optional: override.optional ?? false,
    manifestStatus: manifestStep.status,
    isolationParams: override.isolation_params ?? ['story_id'],
    invokeOptions: {
      usesMaxChunks: invoke.uses_max_chunks ?? false,
      maxChunks: invoke.max_chunks ?? (invoke.uses_max_chunks ? 20 : null),
      timeoutMs: invoke.timeout_ms ?? 60_000,
    },
    inactiveNote: manifestStep.status !== 'active' ? inactiveNote : null,
  };
}

function buildCatalog(config: AdminCatalogConfig) {
  const manifest = loadManifest();
  const inactiveNote = config.inactive_note ?? 'Not active in activation.yaml';
  const stages: CatalogStage[] = [];
  const steps: CatalogStep[] = [];
  const errors: string[] = [];

  for (const stage of config.stages) {
    const stepIds: string[] = [];
    for (const override of stage.steps) {
      const manifestStep = stepById(manifest.steps, override.id);
      if (!manifestStep) {
        errors.push(`Unknown step id in pipeline-admin-catalog.yaml: ${override.id}`);
        continue;
      }
      if (!manifestStep.deploy_name) {
        errors.push(`Step ${override.id} has no deploy_name in manifest`);
        continue;
      }
      stepIds.push(override.id);
      steps.push(mergeStep(override, stage, manifestStep, inactiveNote));
    }
    stages.push({
      id: stage.id,
      label: stage.label,
      scope: stage.scope,
      stepIds,
    });
  }

  if (errors.length) {
    throw new Error(errors.join('\n'));
  }

  return { stages, steps };
}

function writeIfChanged(filePath: string, content: string): boolean {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const next = content.endsWith('\n') ? content : content + '\n';
  if (fs.existsSync(filePath)) {
    const prev = fs.readFileSync(filePath, 'utf8');
    if (prev === next) return false;
    if (checkOnly) return true;
  } else if (checkOnly) {
    return true;
  }
  fs.writeFileSync(filePath, next);
  return true;
}

function tsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

function generateTs(catalog: { stages: CatalogStage[]; steps: CatalogStep[] }): string {
  const stepIds = catalog.steps.map((s) => s.id);
  const lines: string[] = [
    TS_BANNER,
    '',
    'export type PipelineStepId =',
    stepIds.map((id) => `  | ${tsStringLiteral(id)}`).join('\n'),
    '',
    'export type PipelineStageId =',
    catalog.stages.map((s) => `  | ${tsStringLiteral(s.id)}`).join('\n'),
    '',
    'export type PipelineInvokeOptions = {',
    '  usesMaxChunks: boolean',
    '  maxChunks: number | null',
    '  timeoutMs: number',
    '}',
    '',
    'export type PipelineCatalogStep = {',
    '  id: PipelineStepId',
    '  deployName: string',
    '  label: string',
    '  stageId: PipelineStageId',
    '  stageLabel: string',
    '  scope: string',
    '  optional: boolean',
    '  manifestStatus: string',
    '  isolationParams: string[]',
    '  invokeOptions: PipelineInvokeOptions',
    '  inactiveNote: string | null',
    '}',
    '',
    'export type PipelineCatalogStage = {',
    '  id: PipelineStageId',
    '  label: string',
    '  scope: string',
    '  stepIds: PipelineStepId[]',
    '}',
    '',
    'export const PIPELINE_STAGES: PipelineCatalogStage[] = ' +
      JSON.stringify(catalog.stages, null, 2),
    '',
    'export const PIPELINE_STEPS: PipelineCatalogStep[] = ' +
      JSON.stringify(catalog.steps, null, 2),
    '',
    'export const PIPELINE_DEPLOY_ALLOWLIST = new Set<string>([',
    ...catalog.steps.map((s) => `  ${tsStringLiteral(s.deployName)},`),
    '])',
    '',
    'const STEP_BY_ID = new Map<PipelineStepId, PipelineCatalogStep>(',
    '  PIPELINE_STEPS.map((s) => [s.id, s]),',
    ')',
    '',
    'const STEP_BY_DEPLOY = new Map<string, PipelineCatalogStep>(',
    '  PIPELINE_STEPS.map((s) => [s.deployName, s]),',
    ')',
    '',
    'export function getPipelineStep(id: PipelineStepId): PipelineCatalogStep | undefined {',
    '  return STEP_BY_ID.get(id)',
    '}',
    '',
    'export function resolveDeployName(step: string): string | null {',
    '  const byId = STEP_BY_ID.get(step as PipelineStepId)',
    '  if (byId) return byId.deployName',
    '  if (PIPELINE_DEPLOY_ALLOWLIST.has(step)) return step',
    '  return null',
    '}',
    '',
    'export function usesMaxChunks(deployName: string): boolean {',
    '  return STEP_BY_DEPLOY.get(deployName)?.invokeOptions.usesMaxChunks ?? false',
    '}',
    '',
    'export function getInvokeOptions(deployName: string): PipelineInvokeOptions {',
    '  const step = STEP_BY_DEPLOY.get(deployName)',
    '  return step?.invokeOptions ?? { usesMaxChunks: false, maxChunks: null, timeoutMs: 60_000 }',
    '}',
    '',
    'export function getStepsForStage(stageId: PipelineStageId): PipelineCatalogStep[] {',
    '  return PIPELINE_STEPS.filter((s) => s.stageId === stageId)',
    '}',
    '',
  ];
  return lines.join('\n');
}

function generateMd(catalog: { stages: CatalogStage[]; steps: CatalogStep[] }): string {
  const lines = [
    GENERATED_BANNER,
    '# Pipeline catalog (admin)',
    '',
    'Story-scoped stages and steps for the admin pipeline UI. Merged from `pipeline-admin-catalog.yaml` and `manifest.yaml`.',
    '',
  ];

  for (const stage of catalog.stages) {
    lines.push(`## ${stage.label} (\`${stage.id}\`)`, '');
    lines.push('| Step | Deploy | Status | Optional | Isolation |');
    lines.push('|------|--------|--------|----------|-----------|');
    for (const step of catalog.steps.filter((s) => s.stageId === stage.id)) {
      lines.push(
        `| ${step.id} | \`${step.deployName}\` | ${step.manifestStatus} | ${step.optional ? 'yes' : '—'} | ${step.isolationParams.join(', ')} |`,
      );
    }
    lines.push('');
  }

  lines.push('_Generated from pipeline-admin-catalog.yaml + manifest.yaml._');
  return lines.join('\n');
}

function main() {
  const config = loadConfig();
  const catalog = buildCatalog(config);
  let changed = false;

  if (writeIfChanged(TS_OUT, generateTs(catalog))) changed = true;
  if (writeIfChanged(MD_OUT, generateMd(catalog))) changed = true;

  if (checkOnly && changed) {
    console.error('agents:pipeline-catalog:check failed — catalog is stale. Run: npm run agents:pipeline-catalog');
    process.exit(1);
  }
  if (checkOnly) {
    console.log('agents:pipeline-catalog:check OK');
  } else {
    console.log('agents:pipeline-catalog OK' + (changed ? ' (updated)' : ''));
  }
}

main();
