import fs from 'fs';
import path from 'path';
import yaml from 'yaml';
import { GENERATED_BANNER, REPO_ROOT } from './agents-lib.ts';

const checkOnly = process.argv.includes('--check');

const CONFIG_PATH = path.join(REPO_ROOT, 'doxa-agents', 'ops', 'purge-engine-tables.yaml');
const ROUTINE_PATH = path.join(REPO_ROOT, 'supabase', 'routines', 'purge_engine_data.sql');
const DOCS_PATH = path.join(REPO_ROOT, 'doxa-agents', 'docs', 'generated', 'purge-engine.md');

const SQL_BANNER = `-- AUTO-GENERATED by scripts/generate-purge-engine.ts
-- Source: doxa-agents/ops/purge-engine-tables.yaml
-- Regenerate: npm run agents:refresh
-- Re-apply after table list changes: run this file in Supabase SQL Editor
`;

interface PurgeConfig {
  version: number;
  preserve_tables: string[];
  truncate_groups: { name: string; tables: string[] }[];
  truncate_tables: string[];
  optional_truncate_tables: string[];
  topics_clear_columns: string[];
}

function loadConfig(): PurgeConfig {
  const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
  return yaml.parse(raw) as PurgeConfig;
}

function qualify(table: string): string {
  return `public.${table}`;
}

function regclass(table: string): string {
  return `'${qualify(table)}'::regclass`;
}

function buildFunctionBody(cfg: PurgeConfig): string {
  const lines: string[] = [
    'CREATE OR REPLACE FUNCTION public.purge_engine_data()',
    'RETURNS jsonb',
    'LANGUAGE plpgsql',
    'SECURITY DEFINER',
    'SET search_path = public',
    'AS $function$',
    'DECLARE',
    '  v_truncated text[] := array[]::text[];',
    '  v_skipped text[] := array[]::text[];',
    '  v_topics_updated boolean := false;',
    '  v_set_parts text[] := array[]::text[];',
    '  v_col text;',
    'BEGIN',
  ];

  for (const group of cfg.truncate_groups) {
    const first = group.tables[0];
    const list = group.tables.map((t) => qualify(t)).join(', ');
    const label = group.name ?? first;
    lines.push(`  -- group: ${label}`);
    lines.push(`  IF ${regclass(first)} IS NOT NULL THEN`);
    lines.push(
      `    EXECUTE 'TRUNCATE TABLE ${list} RESTART IDENTITY CASCADE';`,
    );
    lines.push(`    v_truncated := v_truncated || ARRAY[${group.tables.map((t) => `'${t}'`).join(', ')}];`);
    lines.push('  ELSE');
    lines.push(`    v_skipped := v_skipped || ARRAY['${label}'];`);
    lines.push('  END IF;');
    lines.push('');
  }

  const allSingles = [
    ...cfg.truncate_tables.map((t) => ({ table: t, optional: false })),
    ...cfg.optional_truncate_tables.map((t) => ({ table: t, optional: true })),
  ];

  for (const { table, optional } of allSingles) {
    const tag = optional ? 'optional' : 'required';
    lines.push(`  -- ${tag}: ${table}`);
    lines.push(`  IF ${regclass(table)} IS NOT NULL THEN`);
    lines.push(`    EXECUTE 'TRUNCATE TABLE ${qualify(table)} RESTART IDENTITY CASCADE';`);
    lines.push(`    v_truncated := array_append(v_truncated, '${table}');`);
    lines.push('  ELSE');
    lines.push(`    v_skipped := array_append(v_skipped, '${table}');`);
    lines.push('  END IF;');
    lines.push('');
  }

  const cols = cfg.topics_clear_columns;
  lines.push('  -- clear topic derived fields (rows preserved)');
  lines.push("  IF to_regclass('public.topics') IS NOT NULL THEN");
  lines.push(`    FOREACH v_col IN ARRAY ARRAY[${cols.map((c) => `'${c}'`).join(', ')}]`);
  lines.push('    LOOP');
  lines.push('      IF EXISTS (');
  lines.push('        SELECT 1 FROM information_schema.columns');
  lines.push("        WHERE table_schema = 'public' AND table_name = 'topics' AND column_name = v_col");
  lines.push('      ) THEN');
  lines.push("        v_set_parts := array_append(v_set_parts, format('%I = NULL', v_col));");
  lines.push('      END IF;');
  lines.push('    END LOOP;');
  lines.push('    IF array_length(v_set_parts, 1) IS NOT NULL THEN');
  lines.push("      EXECUTE 'UPDATE public.topics SET ' || array_to_string(v_set_parts, ', ');");
  lines.push('      v_topics_updated := true;');
  lines.push('    END IF;');
  lines.push('  ELSE');
  lines.push("    v_skipped := array_append(v_skipped, 'topics');");
  lines.push('  END IF;');
  lines.push('');

  lines.push('  RETURN jsonb_build_object(');
  lines.push("    'ok', true,");
  lines.push("    'truncated', v_truncated,");
  lines.push("    'skipped', v_skipped,");
  lines.push("    'topics_cleared', v_topics_updated,");
  lines.push(`    'preserved', ARRAY[${cfg.preserve_tables.map((t) => `'${t}'`).join(', ')}]`);
  lines.push('  );');
  lines.push('END;');
  lines.push('$function$;');
  lines.push('');
  lines.push("COMMENT ON FUNCTION public.purge_engine_data() IS");
  lines.push(
    "  'Wipes pipeline-derived data (stories, claims, clusters, viz, etc.). Preserves sources, domain_throttle, pipeline_runs, users, and topic rows. Source: doxa-agents/ops/purge-engine-tables.yaml';",
  );
  lines.push('');
  lines.push('REVOKE ALL ON FUNCTION public.purge_engine_data() FROM PUBLIC;');
  lines.push('GRANT EXECUTE ON FUNCTION public.purge_engine_data() TO service_role;');

  return lines.join('\n');
}

function buildRoutineSql(cfg: PurgeConfig): string {
  return `${SQL_BANNER}\n${buildFunctionBody(cfg)}\n`;
}

function buildDocs(cfg: PurgeConfig): string {
  const groups = cfg.truncate_groups
    .map((g) => `- **${g.name}**: ${g.tables.map((t) => `\`${t}\``).join(', ')}`)
    .join('\n');
  const tables = cfg.truncate_tables.map((t) => `- \`${t}\``).join('\n');
  const optional = cfg.optional_truncate_tables.map((t) => `- \`${t}\` _(if present)_`).join('\n');
  const preserved = cfg.preserve_tables.map((t) => `- \`${t}\``).join('\n');
  const topicCols = cfg.topics_clear_columns.map((c) => `- \`${c}\``).join('\n');

  return [
    GENERATED_BANNER,
    '# Purge engine data',
    '',
    'Postgres function `public.purge_engine_data()` clears pipeline-derived tables and resets topic summary fields. **Does not** remove source catalog, throttle state, or pipeline run history.',
    '',
    '## Usage',
    '',
    '```sql',
    'SELECT public.purge_engine_data();',
    '```',
    '',
    'Run in Supabase SQL Editor as a privileged role (e.g. service role). After changing the table list in [purge-engine-tables.yaml](../../ops/purge-engine-tables.yaml), run `npm run agents:refresh`, then re-apply [supabase/routines/purge_engine_data.sql](../../../supabase/routines/purge_engine_data.sql) in the SQL Editor.',
    '',
    'Initial install: migration `121_purge_engine_data.sql`.',
    '',
    '## Preserved',
    '',
    preserved,
    '',
    '## Truncate groups',
    '',
    groups,
    '',
    '## Truncate tables',
    '',
    tables,
    '',
    '## Optional (legacy)',
    '',
    optional,
    '',
    '## Topics (rows kept)',
    '',
    'Nulls:',
    '',
    topicCols,
    '',
    '_Generated from doxa-agents/ops/purge-engine-tables.yaml._',
  ].join('\n');
}

function writeIfChanged(filePath: string, content: string): boolean {
  const next = content.endsWith('\n') ? content : content + '\n';
  if (fs.existsSync(filePath)) {
    const prev = fs.readFileSync(filePath, 'utf8');
    if (prev === next) return false;
    if (checkOnly) return true;
  } else if (checkOnly) {
    return true;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, next);
  return true;
}

function main() {
  const cfg = loadConfig();
  const routineSql = buildRoutineSql(cfg);
  const docs = buildDocs(cfg);

  let changed = false;
  if (writeIfChanged(ROUTINE_PATH, routineSql)) changed = true;
  if (writeIfChanged(DOCS_PATH, docs)) changed = true;

  if (checkOnly && changed) {
    console.error('agents:purge-engine:check failed — purge SQL/docs stale. Run: npm run agents:refresh');
    process.exit(1);
  }
  if (checkOnly) {
    console.log('agents:purge-engine:check OK');
  } else {
    console.log('agents:purge-engine OK' + (changed ? ' (updated)' : ''));
  }
}

main();
