-- AUTO-GENERATED by scripts/generate-purge-engine.ts
-- Source: doxa-agents/ops/purge-engine-tables.yaml
-- Regenerate: npm run agents:refresh
-- Re-apply after table list changes: run this file in Supabase SQL Editor

CREATE OR REPLACE FUNCTION public.purge_engine_data()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_truncated text[] := array[]::text[];
  v_skipped text[] := array[]::text[];
  v_topics_updated boolean := false;
  v_set_parts text[] := array[]::text[];
  v_col text;
BEGIN
  -- group: viz
  IF 'public.viz_maps'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.viz_maps, public.viz_nodes, public.viz_edges RESTART IDENTITY CASCADE';
    v_truncated := v_truncated || ARRAY['viz_maps', 'viz_nodes', 'viz_edges'];
  ELSE
    v_skipped := v_skipped || ARRAY['viz'];
  END IF;

  -- required: story_step_runs
  IF 'public.story_step_runs'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.story_step_runs RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'story_step_runs');
  ELSE
    v_skipped := array_append(v_skipped, 'story_step_runs');
  END IF;

  -- required: story_history
  IF 'public.story_history'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.story_history RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'story_history');
  ELSE
    v_skipped := array_append(v_skipped, 'story_history');
  END IF;

  -- required: story_chunks_history
  IF 'public.story_chunks_history'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.story_chunks_history RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'story_chunks_history');
  ELSE
    v_skipped := array_append(v_skipped, 'story_chunks_history');
  END IF;

  -- required: claims_history
  IF 'public.claims_history'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.claims_history RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'claims_history');
  ELSE
    v_skipped := array_append(v_skipped, 'claims_history');
  END IF;

  -- required: events_history
  IF 'public.events_history'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.events_history RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'events_history');
  ELSE
    v_skipped := array_append(v_skipped, 'events_history');
  END IF;

  -- required: positions_history
  IF 'public.positions_history'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.positions_history RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'positions_history');
  ELSE
    v_skipped := array_append(v_skipped, 'positions_history');
  END IF;

  -- required: story_extraction_qa_artifacts
  IF 'public.story_extraction_qa_artifacts'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.story_extraction_qa_artifacts RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'story_extraction_qa_artifacts');
  ELSE
    v_skipped := array_append(v_skipped, 'story_extraction_qa_artifacts');
  END IF;

  -- required: controversy_viewpoints
  IF 'public.controversy_viewpoints'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.controversy_viewpoints RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'controversy_viewpoints');
  ELSE
    v_skipped := array_append(v_skipped, 'controversy_viewpoints');
  END IF;

  -- required: topic_controversies
  IF 'public.topic_controversies'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.topic_controversies RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'topic_controversies');
  ELSE
    v_skipped := array_append(v_skipped, 'topic_controversies');
  END IF;

  -- required: controversy_cluster_lineage
  IF 'public.controversy_cluster_lineage'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.controversy_cluster_lineage RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'controversy_cluster_lineage');
  ELSE
    v_skipped := array_append(v_skipped, 'controversy_cluster_lineage');
  END IF;

  -- required: controversy_cluster_agreements
  IF 'public.controversy_cluster_agreements'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.controversy_cluster_agreements RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'controversy_cluster_agreements');
  ELSE
    v_skipped := array_append(v_skipped, 'controversy_cluster_agreements');
  END IF;

  -- required: controversy_clusters
  IF 'public.controversy_clusters'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.controversy_clusters RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'controversy_clusters');
  ELSE
    v_skipped := array_append(v_skipped, 'controversy_clusters');
  END IF;

  -- required: agreement_cluster_relationships
  IF 'public.agreement_cluster_relationships'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_cluster_relationships RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_cluster_relationships');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_cluster_relationships');
  END IF;

  -- required: agreement_cluster_pair_candidates
  IF 'public.agreement_cluster_pair_candidates'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_cluster_pair_candidates RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_cluster_pair_candidates');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_cluster_pair_candidates');
  END IF;

  -- required: agreement_cluster_positions
  IF 'public.agreement_cluster_positions'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_cluster_positions RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_cluster_positions');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_cluster_positions');
  END IF;

  -- required: agreement_cluster_claims
  IF 'public.agreement_cluster_claims'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_cluster_claims RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_cluster_claims');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_cluster_claims');
  END IF;

  -- required: agreement_clusters
  IF 'public.agreement_clusters'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_clusters RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_clusters');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_clusters');
  END IF;

  -- required: agreement_summary_cache
  IF 'public.agreement_summary_cache'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_summary_cache RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_summary_cache');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_summary_cache');
  END IF;

  -- required: agreement_cluster_migrations
  IF 'public.agreement_cluster_migrations'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.agreement_cluster_migrations RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'agreement_cluster_migrations');
  ELSE
    v_skipped := array_append(v_skipped, 'agreement_cluster_migrations');
  END IF;

  -- required: position_relationships
  IF 'public.position_relationships'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.position_relationships RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'position_relationships');
  ELSE
    v_skipped := array_append(v_skipped, 'position_relationships');
  END IF;

  -- required: position_pair_candidates
  IF 'public.position_pair_candidates'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.position_pair_candidates RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'position_pair_candidates');
  ELSE
    v_skipped := array_append(v_skipped, 'position_pair_candidates');
  END IF;

  -- required: position_pending_subtopics
  IF 'public.position_pending_subtopics'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.position_pending_subtopics RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'position_pending_subtopics');
  ELSE
    v_skipped := array_append(v_skipped, 'position_pending_subtopics');
  END IF;

  -- required: pending_subtopics
  IF 'public.pending_subtopics'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.pending_subtopics RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'pending_subtopics');
  ELSE
    v_skipped := array_append(v_skipped, 'pending_subtopics');
  END IF;

  -- required: canonical_positions
  IF 'public.canonical_positions'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.canonical_positions RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'canonical_positions');
  ELSE
    v_skipped := array_append(v_skipped, 'canonical_positions');
  END IF;

  -- required: events
  IF 'public.events'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.events RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'events');
  ELSE
    v_skipped := array_append(v_skipped, 'events');
  END IF;

  -- required: claim_relationships
  IF 'public.claim_relationships'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.claim_relationships RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'claim_relationships');
  ELSE
    v_skipped := array_append(v_skipped, 'claim_relationships');
  END IF;

  -- required: claims
  IF 'public.claims'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.claims RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'claims');
  ELSE
    v_skipped := array_append(v_skipped, 'claims');
  END IF;

  -- required: stories
  IF 'public.stories'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.stories RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'stories');
  ELSE
    v_skipped := array_append(v_skipped, 'stories');
  END IF;

  -- required: topic_relationships
  IF 'public.topic_relationships'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.topic_relationships RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'topic_relationships');
  ELSE
    v_skipped := array_append(v_skipped, 'topic_relationships');
  END IF;

  -- optional: narrative_viewpoint_links
  IF 'public.narrative_viewpoint_links'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.narrative_viewpoint_links RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'narrative_viewpoint_links');
  ELSE
    v_skipped := array_append(v_skipped, 'narrative_viewpoint_links');
  END IF;

  -- optional: narratives
  IF 'public.narratives'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.narratives RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'narratives');
  ELSE
    v_skipped := array_append(v_skipped, 'narratives');
  END IF;

  -- optional: viewpoint_theses
  IF 'public.viewpoint_theses'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.viewpoint_theses RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'viewpoint_theses');
  ELSE
    v_skipped := array_append(v_skipped, 'viewpoint_theses');
  END IF;

  -- optional: viewpoints
  IF 'public.viewpoints'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.viewpoints RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'viewpoints');
  ELSE
    v_skipped := array_append(v_skipped, 'viewpoints');
  END IF;

  -- optional: claim_archetypes
  IF 'public.claim_archetypes'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.claim_archetypes RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'claim_archetypes');
  ELSE
    v_skipped := array_append(v_skipped, 'claim_archetypes');
  END IF;

  -- optional: archetypes
  IF 'public.archetypes'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.archetypes RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'archetypes');
  ELSE
    v_skipped := array_append(v_skipped, 'archetypes');
  END IF;

  -- clear topic derived fields (rows preserved)
  IF to_regclass('public.topics') IS NOT NULL THEN
    FOREACH v_col IN ARRAY ARRAY['summary', 'topic_description', 'topic_embedding']
    LOOP
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'topics' AND column_name = v_col
      ) THEN
        v_set_parts := array_append(v_set_parts, format('%I = NULL', v_col));
      END IF;
    END LOOP;
    IF array_length(v_set_parts, 1) IS NOT NULL THEN
      EXECUTE 'UPDATE public.topics SET ' || array_to_string(v_set_parts, ', ');
      v_topics_updated := true;
    END IF;
  ELSE
    v_skipped := array_append(v_skipped, 'topics');
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'truncated', v_truncated,
    'skipped', v_skipped,
    'topics_cleared', v_topics_updated,
    'preserved', ARRAY['sources', 'domain_throttle', 'pipeline_runs', 'users', 'topics']
  );
END;
$function$;

COMMENT ON FUNCTION public.purge_engine_data() IS
  'Wipes pipeline-derived data (stories, claims, clusters, viz, etc.). Preserves sources, domain_throttle, pipeline_runs, users, and topic rows. Source: doxa-agents/ops/purge-engine-tables.yaml';

REVOKE ALL ON FUNCTION public.purge_engine_data() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.purge_engine_data() TO service_role;
