-- AUTO-GENERATED by scripts/generate-purge-engine.ts
-- Source: doxa-agents/ops/purge-engine-tables.yaml
-- Regenerate: npm run agents:refresh
-- Re-apply after table list changes: run this file in Supabase SQL Editor

CREATE OR REPLACE FUNCTION public.purge_engine_data()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_truncated text[] := array[]::text[];
  v_skipped text[] := array[]::text[];
  v_topics_updated boolean := false;
  v_set_parts text[] := array[]::text[];
  v_col text;
BEGIN
  -- required: story_step_runs
  IF 'public.story_step_runs'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.story_step_runs RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'story_step_runs');
  ELSE
    v_skipped := array_append(v_skipped, 'story_step_runs');
  END IF;

  -- required: story_history
  IF 'public.story_history'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.story_history RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'story_history');
  ELSE
    v_skipped := array_append(v_skipped, 'story_history');
  END IF;

  -- required: graph_processing_attempts
  IF 'public.graph_processing_attempts'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_processing_attempts RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_processing_attempts');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_processing_attempts');
  END IF;

  -- required: graph_processing_jobs
  IF 'public.graph_processing_jobs'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_processing_jobs RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_processing_jobs');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_processing_jobs');
  END IF;

  -- required: graph_entity_alias_candidates
  IF 'public.graph_entity_alias_candidates'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_entity_alias_candidates RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_entity_alias_candidates');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_entity_alias_candidates');
  END IF;

  -- required: graph_controversy_subjects
  IF 'public.graph_controversy_subjects'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_controversy_subjects RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_controversy_subjects');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_controversy_subjects');
  END IF;

  -- required: graph_assessments
  IF 'public.graph_assessments'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_assessments RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_assessments');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_assessments');
  END IF;

  -- required: graph_people
  IF 'public.graph_people'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_people RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_people');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_people');
  END IF;

  -- required: graph_evidence_excerpts
  IF 'public.graph_evidence_excerpts'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_evidence_excerpts RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_evidence_excerpts');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_evidence_excerpts');
  END IF;

  -- required: graph_topic_links
  IF 'public.graph_topic_links'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_topic_links RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_topic_links');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_topic_links');
  END IF;

  -- required: graph_controversy_evidence
  IF 'public.graph_controversy_evidence'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_controversy_evidence RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_controversy_evidence');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_controversy_evidence');
  END IF;

  -- required: graph_viewpoints
  IF 'public.graph_viewpoints'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_viewpoints RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_viewpoints');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_viewpoints');
  END IF;

  -- required: graph_controversies
  IF 'public.graph_controversies'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_controversies RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_controversies');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_controversies');
  END IF;

  -- required: graph_questions
  IF 'public.graph_questions'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.graph_questions RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'graph_questions');
  ELSE
    v_skipped := array_append(v_skipped, 'graph_questions');
  END IF;

  -- required: l3_proposal_ops
  IF 'public.l3_proposal_ops'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.l3_proposal_ops RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'l3_proposal_ops');
  ELSE
    v_skipped := array_append(v_skipped, 'l3_proposal_ops');
  END IF;

  -- required: l3_proposals
  IF 'public.l3_proposals'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.l3_proposals RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'l3_proposals');
  ELSE
    v_skipped := array_append(v_skipped, 'l3_proposals');
  END IF;

  -- required: l3_review_queue
  IF 'public.l3_review_queue'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.l3_review_queue RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'l3_review_queue');
  ELSE
    v_skipped := array_append(v_skipped, 'l3_review_queue');
  END IF;

  -- required: l3_runs
  IF 'public.l3_runs'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.l3_runs RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'l3_runs');
  ELSE
    v_skipped := array_append(v_skipped, 'l3_runs');
  END IF;

  -- required: l3_gold_negatives
  IF 'public.l3_gold_negatives'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.l3_gold_negatives RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'l3_gold_negatives');
  ELSE
    v_skipped := array_append(v_skipped, 'l3_gold_negatives');
  END IF;

  -- required: l3_bots
  IF 'public.l3_bots'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.l3_bots RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'l3_bots');
  ELSE
    v_skipped := array_append(v_skipped, 'l3_bots');
  END IF;

  -- required: stories
  IF 'public.stories'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.stories RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'stories');
  ELSE
    v_skipped := array_append(v_skipped, 'stories');
  END IF;

  -- required: topic_relationships
  IF 'public.topic_relationships'::regclass IS NOT NULL THEN
    EXECUTE 'TRUNCATE TABLE public.topic_relationships RESTART IDENTITY CASCADE';
    v_truncated := array_append(v_truncated, 'topic_relationships');
  ELSE
    v_skipped := array_append(v_skipped, 'topic_relationships');
  END IF;

  -- clear topic derived fields (rows preserved)
  IF to_regclass('public.topics') IS NOT NULL THEN
    FOREACH v_col IN ARRAY ARRAY['summary', 'topic_description', 'topic_embedding']
    LOOP
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'topics' AND column_name = v_col
      ) THEN
        v_set_parts := array_append(v_set_parts, format('%I = NULL', v_col));
      END IF;
    END LOOP;
    IF array_length(v_set_parts, 1) IS NOT NULL THEN
      EXECUTE 'UPDATE public.topics SET ' || array_to_string(v_set_parts, ', ');
      v_topics_updated := true;
    END IF;
  ELSE
    v_skipped := array_append(v_skipped, 'topics');
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'truncated', v_truncated,
    'skipped', v_skipped,
    'topics_cleared', v_topics_updated,
    'preserved', ARRAY['sources', 'domain_throttle', 'pipeline_runs', 'users', 'topics']
  );
END;
$function$;

COMMENT ON FUNCTION public.purge_engine_data() IS
  'Wipes pipeline-derived data (stories, claims, clusters, etc.). Preserves sources, domain_throttle, pipeline_runs, users, and topic rows. Source: doxa-agents/ops/purge-engine-tables.yaml';

REVOKE ALL ON FUNCTION public.purge_engine_data() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.purge_engine_data() TO service_role;
