-- 005_shared_facts_wikipedia_style.sql
-- Replace many small key-value pairs with 1-2 Wikipedia-style section headers and ~5 paragraphs of content per topic.
-- Run after 001, 002, seed.sql, and 004_seed_core_facts.sql. Paragraphs are separated by \n\n in values.

-- Node 1: Welfare eligibility (5 paragraphs across 2 sections)
UPDATE nodes SET shared_facts = E'{
  "Legal and policy context": "Federal eligibility for most means-tested benefits is governed by the Personal Responsibility and Work Opportunity Reconciliation Act (PRWORA) of 1996, which distinguishes between qualified and non-qualified immigrants. Undocumented immigrants are generally ineligible for SSI, TANF, federal Medicaid (with limited exceptions), and SNAP.\n\nState and local governments have discretion to extend additional benefits. Some states provide state-funded health care, in-state tuition, or driver licenses regardless of federal status. Eligibility therefore varies significantly by jurisdiction and by program.\n\nCongress has repeatedly debated but not passed comprehensive immigration reform that would alter benefit eligibility. Enforcement of immigration status for benefits varies by agency and program.",
  "Definitions and scope": "Undocumented immigrants are foreign nationals present in the United States without legal authorization to be in the United States. The term does not distinguish between those who entered without inspection and those who overstayed a visa.\n\nCertain services remain available regardless of status. The Emergency Medical Treatment and Labor Act (EMTALA) requires participating hospitals to provide emergency care to anyone who needs it. Public K–12 education is guaranteed to all children residing in the United States under Plyler v. Doe (1982). WIC and school lunch programs may be accessible to children regardless of parent status in some contexts."
}'::jsonb
WHERE id = '10000000-0000-0000-0000-000000000001';

-- Node 2: CBP encounters (5 paragraphs across 2 sections)
UPDATE nodes SET shared_facts = E'{
  "How CBP defines an encounter": "U.S. Customs and Border Protection (CBP) defines an encounter as a recorded interaction between CBP and a noncitizen who is apprehended or deemed inadmissible at or between ports of entry. The same individual can be counted more than once if encountered in multiple months or in different locations.\n\nCBP distinguishes between encounters at ports of entry (e.g., airports, land ports) and those between ports of entry (apprehensions along the border). The statistics do not by themselves indicate how many unique individuals were encountered in a given period. CBP has at times published estimates of unique individuals to address this.\n\nPolicies such as Title 42 and the Migrant Protection Protocols have affected whether individuals are expelled, returned, or processed under immigration law, which in turn affects how encounters are counted and reported.",
  "Context for the data": "Encounter data are published monthly and used by policymakers, researchers, and the media to describe trends in border enforcement and migration flows. Interpretation often depends on whether the focus is enforcement workload, deterrence, or the number of people seeking to enter the United States.\n\nCritics of single-number summaries argue that the same person can be counted multiple times and that encounters include people seeking legal asylum, which can inflate the perception of crisis. Defenders of the metric argue that it reflects the real operational burden on CBP and the scale of border challenges."
}'::jsonb
WHERE id = '10000000-0000-0000-0000-000000000002';

-- Node 3: Minneapolis ICE protest (5 paragraphs across 2 sections)
UPDATE nodes SET shared_facts = E'{
  "Context and events": "In 2018, Immigration and Customs Enforcement (ICE) conducted enforcement operations in the Minneapolis–Saint Paul area. ICE is the federal agency responsible for enforcing immigration laws within the United States, including locating and detaining people who are in the country without authorization or who have violated immigration terms.\n\nCommunity members and advocacy groups organized protests at or near locations where ICE was believed to be operating, with the stated aim of discouraging arrests or providing support to affected families. Some protests involved blocking access to buildings or vehicles. Protesters described their actions as non-violent civil disobedience; law enforcement and some observers raised concerns about safety and obstruction.\n\nThe events drew national attention and highlighted tensions between federal immigration enforcement and local communities.",
  "Aftermath and policy": "Minneapolis had previously considered or adopted policies limiting local law enforcement cooperation with ICE in certain contexts. The protests reinforced debates over sanctuary policies, federalism, and the role of local government in immigration enforcement.\n\nQuestions raised in the aftermath included the scope of ICE''s authority, the role of civil disobedience, and the impact of enforcement on immigrant communities. Similar protests and enforcement operations have occurred in other cities, with ongoing litigation and policy debate over the limits of federal and state power."
}'::jsonb
WHERE id = '10000000-0000-0000-0000-000000000003';

-- Node 4: U.S. asylum process (5 paragraphs across 2 sections)
UPDATE nodes SET shared_facts = E'{
  "Legal framework": "Asylum is a form of protection available to individuals who meet the definition of a refugee under U.S. law and are physically present in the United States or at a port of entry. The Immigration and Nationality Act (INA) and the Refugee Act of 1980 incorporate the United Nations Refugee Convention into U.S. law.\n\nTo qualify for asylum, an applicant must demonstrate a well-founded fear of persecution on account of race, religion, nationality, membership in a particular social group, or political opinion. The burden of proof is on the applicant. Asylum can be granted by an asylum officer (affirmative asylum) or by an immigration judge in removal proceedings (defensive asylum).\n\nApproved asylum applicants may apply for lawful permanent residence (a green card) one year after being granted asylum. Denied applicants may be placed in removal proceedings unless they are otherwise authorized to remain.",
  "Process and backlogs": "The process typically involves filing an application, being interviewed or appearing in court, and receiving a decision. Backlogs in the immigration court system and in U.S. Citizenship and Immigration Services (USCIS) have led to long wait times—in some cases years.\n\nApplicants may be detained or released on parole or bond while their cases are pending, depending on the circumstances. Policies such as Remain in Mexico and the use of expedited removal have been the subject of litigation and policy debate. There is no annual numerical cap on asylum grants, unlike the refugee admissions program."
}'::jsonb
WHERE id = '10000000-0000-0000-0000-000000000004';

-- Node 5: Refugee vs asylee (5 paragraphs across 2 sections)
UPDATE nodes SET shared_facts = E'{
  "Same standard, different location": "Under U.S. law, both refugees and asylees must meet the same definition of a refugee: a person who is unable or unwilling to return to their country of nationality because of persecution or a well-founded fear of persecution on account of race, religion, nationality, membership in a particular social group, or political opinion. The main difference is where the person is when they apply for protection.\n\nRefugees are processed and admitted from outside the United States. They typically apply through the U.S. Refugee Admissions Program (USRAP), often from a country of first asylum or through a referral from the UN Refugee Agency (UNHCR). They undergo vetting abroad and, if approved, are admitted to the United States with refugee status. The number of refugees admitted each year is subject to a ceiling set by the President in consultation with Congress.\n\nAsylees are people who request asylum after arriving in the United States or at a port of entry. They may have entered with a visa or without inspection. Once asylum is granted, they have similar rights and benefits as refugees.",
  "Definitions and comparison": "Both refugees and asylees may apply for a green card one year after being granted status. The legal standard for protection is the same; the difference is procedural and geographic.\n\nRefugee resettlement is often described as more controlled and predictable because applicants are vetted abroad before travel. Asylum can be sought by anyone who reaches the United States and meets the standard, which has led to debate over border enforcement, backlogs, and the distinction between the two pathways. There is no annual numerical cap on asylum grants."
}'::jsonb
WHERE id = '10000000-0000-0000-0000-000000000005';
