-- 008_trending_topics_wikipedia_style.sql
-- Replace the five trending topics with Wikipedia-style titles and content.
-- Run after 001–007 (and seed). Updates nodes, node_perspectives; clears relationships and sources for these nodes.

-- Remove old relationships so "Related topics" is not misleading
DELETE FROM node_relationships
WHERE source_node_id IN (
  '10000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000003', '10000000-0000-0000-0000-000000000004',
  '10000000-0000-0000-0000-000000000005'
) OR target_node_id IN (
  '10000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000003', '10000000-0000-0000-0000-000000000004',
  '10000000-0000-0000-0000-000000000005'
);

-- Remove old sources that referred to previous topics
DELETE FROM sources
WHERE node_id IN (
  '10000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000003', '10000000-0000-0000-0000-000000000004',
  '10000000-0000-0000-0000-000000000005'
);

-- ========== NODE 001: Minneapolis ICE protests ==========
UPDATE nodes SET
  question = 'Minneapolis ICE protests',
  core_facts = E'The Minneapolis ICE protests were a series of demonstrations in the Minneapolis–Saint Paul area in 2018 in response to enforcement operations by U.S. Immigration and Customs Enforcement (ICE). ICE is the federal agency within the Department of Homeland Security responsible for enforcing immigration laws within the United States, including locating and detaining people who are in the country without authorization or who have violated immigration terms.

Community members and advocacy groups organized protests at or near locations where ICE was believed to be operating. Protesters gathered with the stated aim of discouraging arrests or providing support to affected families. Some protests involved blocking access to buildings or vehicles; participants described their actions as non-violent civil disobedience, while law enforcement and some observers raised concerns about safety and obstruction.

The events drew national attention and highlighted tensions between federal immigration enforcement and local communities. Minneapolis had previously considered or adopted policies limiting local law enforcement cooperation with ICE in certain contexts. The protests reinforced ongoing debate over sanctuary policies, federalism, and the role of local government in immigration enforcement.',
  shared_facts = $json${
  "Context and events": "In 2018, Immigration and Customs Enforcement (ICE) conducted enforcement operations in the Minneapolis–Saint Paul area. Community members and advocacy groups organized protests at or near locations where ICE was believed to be operating, with the stated aim of discouraging arrests or providing support to affected families. Some protests involved blocking access to buildings or vehicles. Protesters described their actions as non-violent civil disobedience; law enforcement and some observers raised concerns about safety and obstruction.\n\nThe events drew national attention and highlighted tensions between federal immigration enforcement and local communities.",
  "Aftermath and policy": "Minneapolis had previously considered or adopted policies limiting local law enforcement cooperation with ICE in certain contexts. The protests reinforced debates over sanctuary policies, federalism, and the role of local government in immigration enforcement. Questions raised in the aftermath included the scope of ICE's authority, the role of civil disobedience, and the impact of enforcement on immigrant communities. Similar protests and enforcement operations have occurred in other cities, with ongoing litigation and policy debate over the limits of federal and state power."
}$json$::jsonb
WHERE id = '10000000-0000-0000-0000-000000000001';

-- Node 001 perspectives (Minneapolis ICE protests)
UPDATE node_perspectives SET core_claim = 'ICE was conducting lawful enforcement operations when protesters interfered, creating safety risks and obstructing federal law enforcement.', key_arguments = '["ICE has legal authority to enforce immigration laws", "Protesters blocked access and created dangerous situations", "Enforcement actions target individuals who have violated immigration law", "Protest interference undermines rule of law"]'::jsonb, emphasis = 'Emphasizes legal authority and rule of law' WHERE node_id = '10000000-0000-0000-0000-000000000001' AND perspective_id = '00000000-0000-0000-0000-000000000001';
UPDATE node_perspectives SET core_claim = 'Community members organized peaceful protests to protect neighbors from aggressive ICE enforcement that separated families and created fear in immigrant communities.', key_arguments = '["ICE operations created fear and trauma in immigrant communities", "Protesters used non-violent civil disobedience to protect neighbors", "Many targeted individuals had no criminal record", "Community solidarity against what many saw as unjust enforcement"]'::jsonb, emphasis = 'Emphasizes community protection, human rights, and civil disobedience' WHERE node_id = '10000000-0000-0000-0000-000000000001' AND perspective_id = '00000000-0000-0000-0000-000000000002';
UPDATE node_perspectives SET core_claim = 'The protests highlighted conflicts between federal immigration enforcement and local communities, with both sides operating within their perceived rights.', key_arguments = '["Federal agencies have authority but local communities have autonomy", "Voluntary association and community defense are legitimate", "Immigration enforcement creates conflicts between different levels of government", "Solutions should respect both federal law and local community values"]'::jsonb, emphasis = 'Emphasizes federalism, local autonomy, and voluntary association' WHERE node_id = '10000000-0000-0000-0000-000000000001' AND perspective_id = '00000000-0000-0000-0000-000000000003';

-- ========== NODE 002: Election integrity and voting laws ==========
UPDATE nodes SET
  question = 'Election integrity and voting laws',
  core_facts = E'Election integrity and voting laws in the United States refer to the legal and administrative framework governing how elections are conducted and how citizens register and cast ballots. Elections are administered primarily at the state and local level, with federal law setting baseline requirements for federal elections and protecting voting rights.

Key federal statutes include the Voting Rights Act of 1965, which prohibits racial discrimination in voting, and the Help America Vote Act of 2002, which established minimum standards for voting systems and voter registration. States determine rules for voter identification, absentee and mail voting, early voting, and registration deadlines. Debate over election integrity often centers on the balance between securing elections against fraud and ensuring broad access to the ballot.

Controversies have included voter ID requirements, purges of voter rolls, mail-in and absentee voting procedures, and the role of partisan versus nonpartisan election administration. Reform proposals have focused on standardized identification, expanded early and mail voting, independent redistricting, and auditing of election results.',
  shared_facts = $json${
  "Key laws and framework": "The Voting Rights Act of 1965 prohibits racial discrimination in voting and has been amended several times; the Supreme Court's 2013 decision in Shelby County v. Holder limited the reach of federal preclearance of state voting changes. The Help America Vote Act of 2002 established minimum standards for voting systems and voter registration. States set rules for voter ID, absentee and mail voting, early voting, and registration deadlines. Federal law also governs campaign finance disclosure and certain aspects of federal elections.\n\nElection administration is carried out by state and local officials, with variation in practices across jurisdictions.",
  "Controversies and reforms": "Debate over election integrity often centers on the balance between securing elections against fraud and ensuring broad access to the ballot. Controversies have included voter ID requirements, purges of voter rolls, mail-in and absentee voting procedures, and the role of partisan versus nonpartisan election administration. Reform proposals have included standardized identification requirements, expanded early and mail voting, independent redistricting commissions, and post-election audits. Allegations of widespread fraud versus voter suppression have been recurring themes in political discourse."
}$json$::jsonb
WHERE id = '10000000-0000-0000-0000-000000000002';

-- Node 002 perspectives (Election integrity and voting laws)
UPDATE node_perspectives SET core_claim = 'Election integrity requires strong voter identification and safeguards against fraud to maintain public confidence in outcomes.', key_arguments = '["Voter ID laws protect against in-person impersonation and bolster confidence", "Mail-in voting should be limited or tightly controlled to reduce fraud risk", "Regular list maintenance and purges prevent ineligible voters from casting ballots", "Election security measures are necessary to preserve trust in democratic institutions"]'::jsonb, emphasis = 'Emphasizes fraud prevention and voter ID' WHERE node_id = '10000000-0000-0000-0000-000000000002' AND perspective_id = '00000000-0000-0000-0000-000000000001';
UPDATE node_perspectives SET core_claim = 'Voting rights and access should be expanded while combating suppression; security and access are compatible with proper funding and oversight.', key_arguments = '["Voter ID and restrictive rules disproportionately burden minority and low-income voters", "Mail-in and early voting increase participation and should be expanded", "Purges and strict registration rules have been used to disenfranchise eligible voters", "Independent administration and federal standards can secure elections while protecting access"]'::jsonb, emphasis = 'Emphasizes access, anti-suppression, and equitable administration' WHERE node_id = '10000000-0000-0000-0000-000000000002' AND perspective_id = '00000000-0000-0000-0000-000000000002';
UPDATE node_perspectives SET core_claim = 'Election rules should be set primarily at the state level with minimal federal intervention; transparency and voluntary standards are preferable to federal mandates.', key_arguments = '["States are best positioned to set registration and voting rules for their populations", "Federal mandates centralize power and can reduce flexibility and innovation", "Transparency and audits matter more than one-size-fits-all rules", "Private and nonprofit efforts can support verification without government overreach"]'::jsonb, emphasis = 'Emphasizes federalism and state discretion' WHERE node_id = '10000000-0000-0000-0000-000000000002' AND perspective_id = '00000000-0000-0000-0000-000000000003';

-- ========== NODE 003: Redistricting and gerrymandering ==========
UPDATE nodes SET
  question = 'Redistricting and gerrymandering',
  core_facts = E'Redistricting is the process of drawing boundaries for electoral districts, typically after each decennial census in the United States. Congressional and state legislative districts are redrawn to reflect population changes and to satisfy the constitutional requirement of one person, one vote. In most states, the state legislature controls the process; some states use independent or bipartisan commissions.

Gerrymandering is the practice of drawing district lines to advantage a particular party or group or to disadvantage another. The term dates to the early 19th century. Partisan gerrymandering aims to maximize one party''s seats relative to its share of the vote; racial gerrymandering involves drawing lines to dilute or concentrate the voting power of racial minorities. The Supreme Court has struck down racial gerrymandering under the Voting Rights Act and the Fourteenth Amendment but has been reluctant to impose a clear standard for partisan gerrymandering.

Reform efforts have focused on independent commissions, transparency, and mathematical or fairness criteria for district design. Debate continues over the role of the federal government, the use of partisan data in mapmaking, and the balance between partisan fairness and other goals such as compactness and respect for communities of interest.',
  shared_facts = $json${
  "Process and legal framework": "Redistricting occurs after each decennial census. Congressional and state legislative districts must have roughly equal population. In most states, the legislature draws the maps; some states use independent or bipartisan commissions. The Voting Rights Act and the Fourteenth Amendment constrain racial gerrymandering; the Supreme Court has invalidated maps that dilute minority voting strength. Partisan gerrymandering has been challenged in court, but the Court has not adopted a single nationwide standard for when it is unconstitutional.\n\nState courts have increasingly ruled on partisan gerrymandering under state constitutions.",
  "Debate and reform": "Reform efforts have focused on independent or bipartisan commissions, public transparency in the process, and criteria such as compactness, competitiveness, and partisan fairness. Critics of current practice argue that legislators choosing their voters undermines democracy; defenders argue that redistricting is inherently political and that courts should not impose a single theory of fairness. Some states have adopted commission-based or criteria-driven processes through ballot initiatives or legislation."
}$json$::jsonb
WHERE id = '10000000-0000-0000-0000-000000000003';

-- Node 003 perspectives (Redistricting and gerrymandering)
UPDATE node_perspectives SET core_claim = 'Redistricting is a legitimate state responsibility; courts should intervene only when maps violate clear standards such as racial discrimination or extreme population deviation.', key_arguments = '["State legislatures have traditional authority to draw districts", "Partisan gerrymandering is a political question without a workable judicial standard", "Racial gerrymandering is already prohibited; further federal intervention is unnecessary", "Independent commissions can be biased and are not constitutionally required"]'::jsonb, emphasis = 'Emphasizes state authority and judicial restraint' WHERE node_id = '10000000-0000-0000-0000-000000000003' AND perspective_id = '00000000-0000-0000-0000-000000000001';
UPDATE node_perspectives SET core_claim = 'Gerrymandering undermines democracy; independent commissions and strong fairness criteria are needed to ensure representative outcomes.', key_arguments = '["Partisan gerrymandering entrenches power and reduces accountability", "Independent commissions produce fairer and more competitive maps", "Federal and state standards should limit extreme partisan advantage", "Communities of interest and minority representation should be protected in the process"]'::jsonb, emphasis = 'Emphasizes fair representation and anti-gerrymandering reform' WHERE node_id = '10000000-0000-0000-0000-000000000003' AND perspective_id = '00000000-0000-0000-0000-000000000002';
UPDATE node_perspectives SET core_claim = 'Redistricting should be as neutral and transparent as possible; federal intervention should be minimal and state-level reform should emphasize process over outcomes.', key_arguments = '["Transparency and public input matter more than federal mandates", "Compactness and neutral criteria reduce gaming", "Independent commissions can work if designed to limit partisan capture", "One-size-fits-all federal rules can undermine state experimentation"]'::jsonb, emphasis = 'Emphasizes transparency and minimal federal role' WHERE node_id = '10000000-0000-0000-0000-000000000003' AND perspective_id = '00000000-0000-0000-0000-000000000003';

-- ========== NODE 004: Tariff policy ==========
UPDATE nodes SET
  question = 'Tariff policy',
  core_facts = E'Tariff policy in the United States refers to the imposition of taxes or duties on imported (and in some cases exported) goods. The U.S. Constitution grants Congress the power to lay and collect taxes, duties, imposts, and excises; tariffs have historically been a major source of federal revenue and a tool of trade policy. Congress has delegated some authority to the executive branch under statutes such as the Trade Expansion Act of 1962 and the Trade Act of 1974.

Since the mid-20th century, the United States has generally pursued multilateral trade liberalization through agreements such as the General Agreement on Tariffs and Trade (GATT) and the World Trade Organization (WTO), reducing average tariff rates. In the 2010s and 2020s, tariff policy returned to prominence with the imposition of broad and targeted tariffs on steel, aluminum, and goods from China, and with debates over the economic and strategic effects of protectionism versus free trade.

Supporters of higher tariffs argue they protect domestic industries and jobs, address unfair foreign practices, and strengthen national security. Critics argue they raise prices for consumers and businesses, invite retaliation, and can reduce overall economic welfare. The balance between protection and openness remains a central issue in U.S. trade policy.',
  shared_facts = $json${
  "U.S. tariff history and authority": "The Constitution gives Congress the power to impose tariffs; Congress has delegated limited authority to the President to adjust tariffs under certain statutory conditions. Tariffs were a primary source of federal revenue until the income tax. The Smoot-Hawley Tariff Act of 1930 raised rates during the Great Depression and is often cited as exacerbating the downturn. After World War II, the U.S. led efforts to lower tariffs through GATT and later the WTO. Average U.S. tariff rates fell significantly in the second half of the 20th century.\n\nCongress and the President continue to debate the use of tariffs for revenue, protection of domestic industry, and leverage in trade negotiations.",
  "Recent debates": "In the 2010s and 2020s, the U.S. imposed significant tariffs on steel, aluminum, and a range of goods from China, citing national security and unfair trade practices. Supporters argued that tariffs protect jobs and industries and pressure trading partners to change behavior. Critics argued that tariffs raise costs for consumers and businesses, provoke retaliation, and can reduce economic growth. The effectiveness and fairness of tariff policy remain contested in both policy and academic circles."
}$json$::jsonb
WHERE id = '10000000-0000-0000-0000-000000000004';

-- Node 004 perspectives (Tariff policy)
UPDATE node_perspectives SET core_claim = 'Tariffs are a legitimate tool to protect domestic industries, counter unfair foreign practices, and strengthen national security.', key_arguments = '["Tariffs protect American jobs and industries from unfair competition", "China and others have used subsidies and intellectual property theft; tariffs are a response", "Strategic industries such as steel and semiconductors warrant protection for security", "Negotiating from a position of strength can yield better trade deals"]'::jsonb, emphasis = 'Emphasizes protection and fair trade' WHERE node_id = '10000000-0000-0000-0000-000000000004' AND perspective_id = '00000000-0000-0000-0000-000000000001';
UPDATE node_perspectives SET core_claim = 'Tariffs should be used sparingly and in coordination with allies; trade policy should protect workers and the environment, not just corporate interests.', key_arguments = '["Broad tariffs often hurt consumers and downstream industries", "Multilateral approaches are more effective than unilateral tariffs", "Labor and environmental standards should be part of trade agreements", "Retaliatory tariffs can harm domestic exporters and escalate trade wars"]'::jsonb, emphasis = 'Emphasizes multilateralism, workers, and targeted use' WHERE node_id = '10000000-0000-0000-0000-000000000004' AND perspective_id = '00000000-0000-0000-0000-000000000002';
UPDATE node_perspectives SET core_claim = 'Free trade generally increases prosperity; tariffs are a tax on consumers and should be reduced or eliminated except in narrow circumstances.', key_arguments = '["Tariffs raise prices and reduce choice for consumers", "Protectionism invites retaliation and reduces global welfare", "Comparative advantage and open markets promote growth and innovation", "Government should not pick winners and losers through trade barriers"]'::jsonb, emphasis = 'Emphasizes free trade and minimal intervention' WHERE node_id = '10000000-0000-0000-0000-000000000004' AND perspective_id = '00000000-0000-0000-0000-000000000003';

-- ========== NODE 005: Twitter Files ==========
UPDATE nodes SET
  question = 'Twitter Files',
  core_facts = E'The Twitter Files are a series of releases of internal Twitter (now X) documents and communications, beginning in late 2022 after entrepreneur Elon Musk acquired the company. Musk granted selected journalists and writers access to internal company materials, including emails, Slack messages, and policy discussions, with the stated goal of transparency about how the platform had moderated content and interacted with governments and other actors.

The releases have covered topics such as the decision to limit the reach of a 2020 New York Post article about Hunter Biden''s laptop, communications with federal agencies regarding misinformation or election integrity, and the suspension of certain high-profile accounts. Supporters of the releases argue they reveal bias, undue government pressure, and opaque content-moderation decisions. Critics argue the releases are selective, lack full context, and have been used to advance a narrative of censorship and partisan bias rather than a complete picture of platform policy.

The Twitter Files have contributed to ongoing debate over the role of social media companies in moderating content, the relationship between government and platforms, and the transparency of moderation decisions. Legal and policy discussions continue about how much platforms should disclose and what obligations they have to users and the public.',
  shared_facts = $json${
  "What the Twitter Files are": "The Twitter Files consist of internal Twitter documents and communications released to selected journalists and writers after Elon Musk acquired the company in 2022. The materials include emails, Slack messages, and internal policy discussions. Releases have addressed decisions such as limiting distribution of the October 2020 New York Post story about Hunter Biden's laptop, communications between Twitter and federal agencies (including the FBI and DHS) regarding misinformation or election-related content, and the suspension and reinstatement of certain accounts, including that of former President Donald Trump.\n\nThe releases were framed by Musk and some of the recipients as revealing how content moderation and coordination with government actors worked in practice.",
  "Reactions and debate": "Supporters of the releases argue they exposed bias in content moderation, inappropriate government pressure on a private platform, and lack of transparency. Critics argue the releases were cherry-picked, lacked sufficient context, and were used to support a predetermined narrative about censorship and partisan bias. Scholars and commentators have debated the significance of government outreach to platforms, the line between coordination and coercion, and the appropriate level of transparency for moderation decisions. The Twitter Files have fed into broader policy debates about Section 230, platform accountability, and the role of government in regulating speech online."
}$json$::jsonb
WHERE id = '10000000-0000-0000-0000-000000000005';

-- Node 005 perspectives (Twitter Files)
UPDATE node_perspectives SET core_claim = 'The Twitter Files revealed inappropriate bias and government pressure on a major platform, undermining trust in both the company and federal agencies.', key_arguments = '["Internal decisions showed bias against conservative voices and stories", "Federal agencies communicated with Twitter in ways that influenced content decisions", "The Hunter Biden laptop story was suppressed before the 2020 election", "Transparency is necessary to hold platforms and government accountable"]'::jsonb, emphasis = 'Emphasizes bias, government pressure, and need for transparency' WHERE node_id = '10000000-0000-0000-0000-000000000005' AND perspective_id = '00000000-0000-0000-0000-000000000001';
UPDATE node_perspectives SET core_claim = 'The Twitter Files were a selective and misleading narrative that overstated government influence and understated legitimate moderation and security concerns.', key_arguments = '["Releases were curated to support a censorship narrative", "Government outreach on misinformation and security is routine and often appropriate", "Content moderation decisions were made under complex and evolving policies", "Full context and comparative analysis are needed before drawing conclusions"]'::jsonb, emphasis = 'Emphasizes context, legitimate moderation, and skepticism of the narrative' WHERE node_id = '10000000-0000-0000-0000-000000000005' AND perspective_id = '00000000-0000-0000-0000-000000000002';
UPDATE node_perspectives SET core_claim = 'Private platforms have the right to set their own rules; the real concern is government coercion and lack of transparency, not private moderation per se.', key_arguments = '["Platforms are private actors and can moderate content as they choose", "Government pressure on platforms to remove or demote content raises First Amendment concerns", "Transparency about both platform and government actions benefits the public", "Solutions should focus on limiting government overreach, not mandating speech"]'::jsonb, emphasis = 'Emphasizes private sovereignty and government overreach' WHERE node_id = '10000000-0000-0000-0000-000000000005' AND perspective_id = '00000000-0000-0000-0000-000000000003';
